// Generated by Selenium IDE
// This test changes text input field, input slider control, select dropdown to 100%, and select checkboxes
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('selenium-demo-test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('selenium-demo-test', async function() {
    await driver.get("https://seleniumbase.io/demo_page")
    await driver.manage().window().setRect({ width: 964, height: 889 })
    await driver.findElement(By.id("myTextInput")).click()
    await driver.findElement(By.id("myTextInput")).sendKeys("hans-khomulia")
    {
      const element = await driver.findElement(By.id("mySlider"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id("mySlider"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.id("mySlider"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("mySlider")).sendKeys("80")
    await driver.findElement(By.id("mySlider")).click()
    await driver.findElement(By.css("tr:nth-child(7) > td:nth-child(2)")).click()
    await driver.findElement(By.id("mySelect")).click()
    {
      const dropdown = await driver.findElement(By.id("mySelect"))
      await dropdown.findElement(By.xpath("//option[. = 'Set to 100%']")).click()
    }
    await driver.findElement(By.id("checkBox2")).click()
    await driver.findElement(By.id("checkBox3")).click()
  })
})
