# Generated by Selenium IDE

#this changes text input, slider, text area, checkbox, checkboxes 
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTugasselenium():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tugasselenium(self):
    self.driver.get("https://seleniumbase.io/demo_page")
    self.driver.set_window_size(1071, 802)
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td:nth-child(2)").click()
    self.driver.find_element(By.ID, "myTextInput").click()
    self.driver.find_element(By.ID, "myTextInput").send_keys("marendra rambang nugroho")
    element = self.driver.find_element(By.ID, "mySlider")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "mySlider")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "mySlider")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "mySlider").send_keys("20")
    self.driver.find_element(By.ID, "mySlider").click()
    self.driver.find_element(By.ID, "myTextInput2").click()
    self.driver.find_element(By.ID, "myButton").click()
    self.driver.find_element(By.ID, "readOnlyText").click()
    self.driver.find_element(By.ID, "mySelect").click()
    dropdown = self.driver.find_element(By.ID, "mySelect")
    dropdown.find_element(By.XPATH, "//option[. = 'Set to 50%']").click()
    self.driver.find_element(By.ID, "checkBox1").click()
    self.driver.find_element(By.ID, "checkBox2").click()
    self.driver.find_element(By.ID, "checkBox3").click()
    self.driver.find_element(By.ID, "checkBox4").click()
    self.driver.find_element(By.ID, "checkBox5").click()
    self.driver.find_element(By.ID, "checkBox5").click()
    self.driver.find_element(By.ID, "myTextarea").click()
    self.driver.find_element(By.ID, "myTextarea").send_keys("anjay mabar")
    self.driver.find_element(By.ID, "pText").click()
  
