# Generated by Selenium IDE

# This test changes the Text Input Field, Input Slider Control, dropdown, CheckBox, textarea
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestselenium():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testselenium(self):
    self.driver.get("https://seleniumbase.io/demo_page")
    self.driver.set_window_size(964, 889)
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td:nth-child(1)").click()
    self.driver.find_element(By.ID, "myTextInput").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2)").click()
    self.driver.find_element(By.ID, "myTextInput").click()
    self.driver.find_element(By.ID, "myTextInput").send_keys("Hans khomulia")
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(1)").click()
    element = self.driver.find_element(By.ID, "mySlider")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "mySlider")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "mySlider")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "mySlider").send_keys("100")
    self.driver.find_element(By.ID, "mySlider").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(2)").click()
    self.driver.find_element(By.ID, "mySelect").click()
    dropdown = self.driver.find_element(By.ID, "mySelect")
    dropdown.find_element(By.XPATH, "//option[. = 'Set to 75%']").click()
    self.driver.find_element(By.ID, "checkBox2").click()
    self.driver.find_element(By.ID, "checkBox4").click()
    self.driver.find_element(By.ID, "myTextarea").click()
    self.driver.find_element(By.ID, "myTextarea").send_keys("adfasdfasdfasdfasdfasdfa")
    self.driver.find_element(By.ID, "myButton").click()
    self.driver.find_element(By.ID, "myButton").click()
    self.driver.find_element(By.ID, "myButton").click()
    element = self.driver.find_element(By.ID, "myButton")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "myButton").click()
    self.driver.find_element(By.ID, "myButton").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(8) > td:nth-child(4)").click()
    self.driver.find_element(By.ID, "radioButton2").click()
    self.driver.find_element(By.ID, "radioButton1").click()
    self.driver.find_element(By.ID, "radioButton2").click()
  
