// Generated by Selenium IDE

// give text input Hardi Kusuma, type text area dolor sit amet, change color from purple into green

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Testing1Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testing1() {
    driver.Navigate().GoToUrl("https://seleniumbase.io/demo_page");
    driver.Manage().Window.Size = new System.Drawing.Size(1221, 640);
    driver.FindElement(By.Id("myTextInput")).Click();
    driver.FindElement(By.Id("myTextInput")).SendKeys("Hardi Kusuma");
    driver.FindElement(By.Id("myTextInput")).SendKeys(Keys.Enter);
    {
      var element = driver.FindElement(By.Id("mySlider"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.Id("mySlider"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.Id("mySlider"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.Id("mySlider")).SendKeys("20");
    driver.FindElement(By.Id("mySlider")).Click();
    driver.FindElement(By.Id("myButton")).Click();
    driver.FindElement(By.Id("pText")).Click();
    driver.FindElement(By.Id("readOnlyText")).Click();
    driver.FindElement(By.Id("readOnlyText")).Click();
    driver.FindElement(By.Id("radioButton2")).Click();
    driver.FindElement(By.Id("checkBox4")).Click();
    driver.FindElement(By.Id("checkBox3")).Click();
    driver.FindElement(By.Id("checkBox2")).Click();
    driver.FindElement(By.Id("myTextarea")).Click();
    driver.FindElement(By.Id("myTextarea")).SendKeys("loirem ipsum dolor sit amet");
  }
}
