# Generated by Selenium IDE

# Tes ini merubah TextInput,Pre-Filled Text Field, HTML SVG with rect,Slider, dropdown, tetx area, checkbox, radiobutton, meterbar
#

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSelenium1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_selenium1(self):
    self.driver.get("https://seleniumbase.io/demo_page")
    self.driver.set_window_size(867, 824)
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td:nth-child(2)").click()
    self.driver.find_element(By.ID, "myTextInput").click()
    self.driver.find_element(By.ID, "myTextInput").send_keys("sdfsdffsdfsd")
    self.driver.find_element(By.ID, "myTextInput2").click()
    self.driver.find_element(By.ID, "myTextInput2").send_keys("Text...aasdd")
    self.driver.find_element(By.ID, "svgRect").click()
    self.driver.find_element(By.ID, "placeholderText").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(2)").click()
    self.driver.find_element(By.ID, "mySlider").send_keys("60")
    self.driver.find_element(By.ID, "mySlider").send_keys("70")
    self.driver.find_element(By.ID, "mySlider").send_keys("80")
    self.driver.find_element(By.ID, "mySlider").send_keys("70")
    self.driver.find_element(By.ID, "mySlider").send_keys("100")
    self.driver.find_element(By.ID, "mySlider").click()
    self.driver.find_element(By.ID, "mySelect").click()
    dropdown = self.driver.find_element(By.ID, "mySelect")
    dropdown.find_element(By.XPATH, "//option[. = 'Set to 50%']").click()
    self.driver.find_element(By.ID, "checkBox3").click()
    self.driver.find_element(By.ID, "checkBox2").click()
    self.driver.find_element(By.ID, "myTextarea").click()
    self.driver.find_element(By.ID, "myTextarea").send_keys("lalalals")
    self.driver.find_element(By.ID, "myButton").click()
    self.driver.find_element(By.ID, "readOnlyText").click()
    self.driver.find_element(By.ID, "progressBar").click()
    self.driver.find_element(By.ID, "meterBar").click()
    self.driver.find_element(By.ID, "radioButton2").click()
  
