// Generated by Selenium IDE

/*
  Controls yang di tes
  Button "Click Me"
  Input Slider Control
  Dan check box tiga yang ketiga

  Assert yang di tes
  Assert value Slider Control
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestAkhirTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testAkhir() {
    driver.Navigate().GoToUrl("https://seleniumbase.io/demo_page");
    driver.Manage().Window.Size = new System.Drawing.Size(892, 660);
    driver.FindElement(By.Id("myButton")).Click();
    {
      var element = driver.FindElement(By.Id("mySlider"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.Id("mySlider"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.Id("mySlider"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.Id("mySlider")).SendKeys("100");
    driver.FindElement(By.Id("mySlider")).Click();
    driver.FindElement(By.Id("checkBox4")).Click();
    {
      string value = driver.FindElement(By.Id("mySlider")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("100"));
    }
  }
}
