# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test2602196265EngelbertKrismanNathanaelP():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_2602196265EngelbertKrismanNathanaelP(self):
    self.driver.get("https://seleniumbase.io/demo_page")
    element = self.driver.find_element(By.ID, "checkBox1")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.ID, "myTextInput").send_keys("Hello")
    self.driver.find_element(By.ID, "myButton").click()
    element = self.driver.find_element(By.ID, "radioButton1")
    if element.is_selected: element.click()
  
