// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

// Di TestScript.java ini code dibawah menunjukan bahwa ada perubahan input text di baris code 47-50, perubahan warna tombol dari hijau ke ungu di code baris 51, dan ketika user menekan URL di code baris 52


public class TestScriptTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testScript() {
    driver.get("https://seleniumbase.io/demo_page");
    driver.manage().window().setSize(new Dimension(785, 816));
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).click();
    driver.findElement(By.id("myTextInput2")).click();
    driver.findElement(By.id("myTextInput2")).sendKeys("isi textt");
    driver.findElement(By.id("myTextInput2")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("myButton")).click();
    driver.findElement(By.id("myLink1")).click();
  }
}
