// Generated by Selenium IDE
//input nama, check box, green to purple
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Testing2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testing2() {
    // Test name: Testing 2
    // Step # | name | target | value
    // 1 | open | /demo_page | 
    driver.get("https://seleniumbase.io/demo_page");
    // 2 | setWindowSize | 1361x730 | 
    driver.manage().window().setSize(new Dimension(1361, 730));
    // 3 | click | id=myTextInput | 
    driver.findElement(By.id("myTextInput")).click();
    // 4 | click | id=myTextInput | 
    driver.findElement(By.id("myTextInput")).click();
    // 5 | type | id=myTextInput | Zefanya
    driver.findElement(By.id("myTextInput")).sendKeys("Zefanya");
    // 6 | click | id=checkBox3 | 
    driver.findElement(By.id("checkBox3")).click();
    // 7 | click | id=progressBar | 
    driver.findElement(By.id("progressBar")).click();
    // 8 | mouseDownAt | id=progressBar | 140.2982177734375,13.296051025390625
    {
      WebElement element = driver.findElement(By.id("progressBar"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 9 | mouseMoveAt | id=progressBar | 140.2982177734375,13.296051025390625
    {
      WebElement element = driver.findElement(By.id("progressBar"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | mouseUpAt | id=progressBar | 140.2982177734375,13.296051025390625
    {
      WebElement element = driver.findElement(By.id("progressBar"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 11 | click | id=progressBar | 
    driver.findElement(By.id("progressBar")).click();
    // 12 | click | id=myTextInput2 | 
    driver.findElement(By.id("myTextInput2")).click();
    // 13 | click | id=myButton | 
    driver.findElement(By.id("myButton")).click();
  }
}
